"""fixes stock control

Revision ID: 7301a0d2fedb
Revises: 55afb4931f5b
Create Date: 2025-05-28 21:34:07.539074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7301a0d2fedb'
down_revision: Union[str, None] = '55afb4931f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flowers', sa.Column('low_stock_threshold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flowers', 'low_stock_threshold')
    # ### end Alembic commands ###
