"""updates flowers

Revision ID: f8790385bbe5
Revises: 7301a0d2fedb
Create Date: 2025-05-29 13:13:51.730419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8790385bbe5'
down_revision: Union[str, None] = '7301a0d2fedb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'loyalty_points')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('loyalty_points', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
